(defun toggle-transparency ()
  (interactive)
  (if (equal "unspecified-bg" (face-background 'default (selected-frame)))
    (set-face-background 'default "#000000" (selected-frame))
    (set-face-background 'default "unspecified-bg" (selected-frame))))
